Traceback (most recent call last):
  File "/Users/moqi/Documents/Code/automate-the-boring-stuff/c10/p176_test1020.py", line 4, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
